services:
  backend:
    volumes: []

  worker:
    volumes:
      - playwright_cache:/root/.cache/ms-playwright

  beat:
    volumes: []

  nginx:
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/conf.d:/etc/nginx/conf.d:ro
      - nginx_logs:/var/log/nginx
